# Generated by Django 6.0.5 on 2026-06-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='experiences/logos/'),
        ),
    ]
