# Generated by Django 6.0.5 on 2026-06-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_pages',
            field=models.IntegerField(default=1),
        ),
    ]
