# Generated by Django 6.0.5 on 2026-06-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_description_en_project_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_jp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='main_hashtag_jp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='regular_hashtags_jp',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_jp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_jp',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
