# Generated by Django 6.0.5 on 2026-06-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='bio_en',
            field=models.TextField(default="Men Feruzxon Muxtarov — Toshkentda yashovchi ijodkor dizayner va art direktor. 5 yildan ortiq vaqt davomida brendlar uchun vizual identitet, raqamli mahsulotlar va marketing materiallarini yarataman. Maqsadim — har bir loyihaga estetika, ma'no va aniqlik kiritish.", null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='bio_jp',
            field=models.TextField(default="Men Feruzxon Muxtarov — Toshkentda yashovchi ijodkor dizayner va art direktor. 5 yildan ortiq vaqt davomida brendlar uchun vizual identitet, raqamli mahsulotlar va marketing materiallarini yarataman. Maqsadim — har bir loyihaga estetika, ma'no va aniqlik kiritish.", null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='bio_ru',
            field=models.TextField(default="Men Feruzxon Muxtarov — Toshkentda yashovchi ijodkor dizayner va art direktor. 5 yildan ortiq vaqt davomida brendlar uchun vizual identitet, raqamli mahsulotlar va marketing materiallarini yarataman. Maqsadim — har bir loyihaga estetika, ma'no va aniqlik kiritish.", null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='bio_uz',
            field=models.TextField(default="Men Feruzxon Muxtarov — Toshkentda yashovchi ijodkor dizayner va art direktor. 5 yildan ortiq vaqt davomida brendlar uchun vizual identitet, raqamli mahsulotlar va marketing materiallarini yarataman. Maqsadim — har bir loyihaga estetika, ma'no va aniqlik kiritish.", null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='name_en',
            field=models.CharField(default='Feruzxon Muxtarov', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='name_jp',
            field=models.CharField(default='Feruzxon Muxtarov', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='name_ru',
            field=models.CharField(default='Feruzxon Muxtarov', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='name_uz',
            field=models.CharField(default='Feruzxon Muxtarov', max_length=255, null=True),
        ),
    ]
