# Generated by Django 6.0.5 on 2026-06-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_aboutme_bio_en_aboutme_bio_jp_aboutme_bio_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_jp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
