# Generated by Django 6.0.5 on 2026-06-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_certificate_title_en_certificate_title_jp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_jp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trait',
            name='text_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trait',
            name='text_jp',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trait',
            name='text_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trait',
            name='text_uz',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
