# Generated by Django 6.0.5 on 2026-06-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_skill_name_en_skill_name_jp_skill_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_jp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='desc_jp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='desc_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='desc_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_jp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
