# Generated by Django 6.0.5 on 2026-06-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_resumedownloadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='about/resume/'),
        ),
    ]
