# Generated by Django 5.2.17 on 2026-10-01 08:23

from django.db import migrations, models



def clear_generated_empty_profile(apps, schema_editor):
    AboutMe = apps.get_model('core', 'AboutMe')
    for profile in AboutMe.objects.filter(name='', bio='', image='', resume_pdf=''):
        fields = ['name_uz', 'name_ru', 'name_jp', 'bio_uz', 'bio_ru', 'bio_jp']
        if all(getattr(profile, field) in ('', AboutMe._meta.get_field(field).default) for field in fields):
            for field in fields:
                setattr(profile, field, '')
            profile.save(update_fields=fields)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_aboutme_resume_pdf'),
    ]

    operations = [
        migrations.RunPython(clear_generated_empty_profile, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='aboutme',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='bio_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='bio_jp',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='bio_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='bio_uz',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='name_en',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='name_jp',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='name_ru',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='name_uz',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
