# Generated by Django 5.2.17 on 2026-10-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_empty_profile_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLimit',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window', models.BigIntegerField(default=0)),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
