# Generated by Django 5.2.17 on 2026-10-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_requestlimit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='projectimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
