# Generated by Django 5.2.17 on 2026-10-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_visitor_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('title_jp', models.CharField(max_length=180, null=True)),
                ('title_en', models.CharField(max_length=180, null=True)),
                ('title_ru', models.CharField(max_length=180, null=True)),
                ('title_uz', models.CharField(max_length=180, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_jp', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='life/')),
                ('is_sample', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
