# Generated by Django 5.2.17 on 2026-10-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_skill_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedownloadlog',
            name='telegram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitordevice',
            name='nickname',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='resumedownloadlog',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]

