# Generated by Django 5.2.17 on 2026-10-07 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_education_links_resume_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/covers/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='core.project')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
