# Generated by Django 5.2.17 on 2026-10-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_projectcover'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='animation_interval',
            field=models.PositiveIntegerField(default=700),
        ),
        migrations.CreateModel(
            name='ExperienceFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='experiences/frames/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animation_frames', to='core.experience')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
