# Generated by Django 5.2.17 on 2026-10-08 13:42

from django.db import migrations, models


def seed_positions(apps,schema_editor):
    Experience=apps.get_model('core','Experience')
    for position,row in enumerate(Experience.objects.order_by('id').all()):
        row.position=position;row.save(update_fields=['position'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_experience_animation_interval_experienceframe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(seed_positions,migrations.RunPython.noop),
    ]
